export const mockEndUsers = [
  {
    id: 1,
    name: "Alex Johnson",
    course: "Business English",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 1,
  },
  {
    id: 2,
    name: "Jamie Smith",
    course: "TOEFL Prep",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 2,
  },
  {
    id: 3,
    name: "Taylor Brown",
    course: "Conversation",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 3,
  },
  {
    id: 4,
    name: "Morgan Wilson",
    course: "Academic English",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 3,
  },
  {
    id: 5,
    name: "Casey Davis",
    course: "Business English",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 3,
  },
  {
    id: 6,
    name: "Riley Martinez",
    course: "IELTS Prep",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 4,
  },
  {
    id: 7,
    name: "Jordan Lee",
    course: "Conversation",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 4,
  },
  {
    id: 8,
    name: "Quinn Thompson",
    course: "Academic English",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 5,
  },
  {
    id: 9,
    name: "Avery Garcia",
    course: "Business English",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 6,
  },
  {
    id: 10,
    name: "Drew Rodriguez",
    course: "TOEFL Prep",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 6,
  },
  {
    id: 11,
    name: "Sam Patel",
    course: "Conversation",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 7,
  },
  {
    id: 12,
    name: "Blake Nguyen",
    course: "Academic English",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 8,
  },
  {
    id: 13,
    name: "Cameron Wright",
    course: "Business English",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 9,
  },
  {
    id: 14,
    name: "Reese Kim",
    course: "IELTS Prep",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 10,
  },
  {
    id: 15,
    name: "Parker Jones",
    course: "Conversation",
    avatar: "/placeholder.svg?height=40&width=40",
    currentStep: 11,
  },
];
